site_name: Evolution CMS CE Docs
site_url: https://docs.evo-cms.com/
repo_url: https://github.com/evocms-community/docs

docs_dir: 'en'

theme:
    name: null
    custom_dir: 'theme/'

nav:
    - 'General Information': '01_General information/'
    - 'For Users': '02_For_users/'
    - 'Tutorials': '05_Tutorials/'
    - 'Extras': '04_Extras/'
    - 'Developers': '03_Developers/'

plugins:
    - search
    - include_dir_to_nav
